version: '3.1'

services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: movie-ratings
      POSTGRES_USER: movie-ratings-user
      POSTGRES_PASSWORD: hj54%#^*(@!A
    ports:
      - 5432:5432